# Generated by Django 4.1.3 on 2023-05-18 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_trend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='attachments',
            field=models.ManyToManyField(blank=True, related_name='post', to='post.postattachment'),
        ),
    ]
