# Generated by Django 4.1.3 on 2023-05-27 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_postreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='postreport',
            name='reason',
            field=models.CharField(default='', max_length=255),
        ),
    ]
